version: '3.8'

services:
  web:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/usr/src/app/public
    ports:
      - 3333:80
  api:
    build: ./
    volumes:
      - ./:/usr/src/app
